
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ClientLayout from "./clientProviders/ClientRedux";

// custom-container m-auto
export default function RootLayout({ children ,params}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} custom-container m-auto relative overflow-x-hidden ${geistMono.variable}   antialiased`}
      >
        
          <ClientLayout>
            <Header params={params}/>
          {children}
          <Footer/>
        </ClientLayout>
        
      </body>
    </html>
  );
}
