import { Cairo } from "next/font/google"; 
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"], 
  weight: ["400", "500", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ClientLayout from "./clientProviders/ClientRedux";

export default function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} custom-container m-auto relative overflow-x-hidden antialiased`}
      >
        <ClientLayout>
          <Header params={params}/>
          {children}
          <Footer/>
        </ClientLayout>
      </body>
    </html>
  );
}
